import {
  getArticleOptionsByCategoryId,
  getCategoryOptions,
  getWordListByLetterCount,
  getWordListPerCount,
} from "@/components/formBuilder/request";
import { speedMap } from "@/utils/constants";

export const controlFields: Record<string, any[]> = {
  "goz-kaslarini-gelistirme": [
    {
      type: "range",
      inputKey: "level",
      value: { key: "level", type: "number", value: 1 },
      name: "Hız",
      min: "1",
      max: "10",
      required: false,
      valueMap: speedMap,
      description: "Nesnenin hareket hızı",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "type",
      value: { key: "type", type: "number", value: 1 },
      name: "Egzersiz Tipi",
      min: "1",
      max: "6",
      required: false,
      description: "Nesne ne yönde nasıl kayacak",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      value: { key: "objectIcon", type: "number", value: 1 },
      inputKey: "objectIcon",
      min: "1",
      max: "10",
      required: false,
      showRangeIcon: true,
      styleClass: "!mb-0",
      name: "Simge",
      description: "Kendinize özel simge seçebilirsiniz",
    },
  ],
  "aktif-gorme-alanini-genisletme-1": [
    {
      type: "range",
      inputKey: "level",
      value: { key: "level", type: "number", value: 1 },
      name: "Hız",
      min: "1",
      max: "10",
      required: false,
      valueMap: speedMap,
      description: "Nesnenin hareket hızı",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "frame",
      value: { key: "frame", type: "number", value: 1 },
      name: "Çerçeve Genişliği",
      min: "1",
      max: "10",
      required: false,
      description: "Köşe noktalarının genişliği",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "grid",
      value: { key: "grid", type: "number", value: 2 },
      name: "Sütun Sayısı",
      min: "1",
      max: "10",
      required: false,
      description: "Rakamlar kaç satır ve sütun gelsin",
      styleClass: "!mb-0",
    },
  ],
  "aktif-gorme-alanini-genisletme-2": [
    {
      type: "range",
      inputKey: "level",
      value: { key: "level", type: "number", value: 1 },
      name: "Hız",
      min: "1",
      max: "10",
      required: false,
      valueMap: speedMap,
      description: "Nesnenin hareket hızı",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "color",
      value: { key: "color", type: "number", value: 1 },
      name: "Çerçeve Genişliği",
      min: "1",
      max: "10",
      required: false,
      showRangeColor: true,
      colorList: {
        "1": "#2ecc71",
        "2": "#f1c40f",
        "3": "#e74c3c",
        "4": "#3498db",
        "5": "#8B4513",
        "6": "#000000",
        "7": "#e67e22",
        "8": "#8e44ad",
        "9": "#ff69b4",
      },
      description: "Köşe noktalarının genişliği",
      styleClass: "!mb-0",
    },
  ],
  "aktif-gorme-alanini-genisletme-3": [
    {
      type: "range",
      inputKey: "level",
      value: { key: "level", type: "number", value: 1 },
      name: "Hız",
      min: "1",
      max: "10",
      required: false,
      valueMap: speedMap,
      description: "Nesnenin hareket hızı",
      styleClass: "!mb-0",
    },
  ],
  "satir-boyu-gorme-uygulamasi": [
    {
      type: "range",
      inputKey: "level",
      value: { key: "level", type: "number", value: 1 },
      name: "Hız",
      min: "1",
      max: "10",
      required: false,
      valueMap: speedMap,
      description: "Nesnenin hareket hızı",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "distance",
      value: { key: "distance", type: "number", value: 1 },
      name: "Merkeze Uzaklık",
      min: "1",
      max: "10",
      required: false,
      description: "İki kelimenin merkeze uzaklığı",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "letterCount",
      value: { key: "letterCount", type: "number", value: 1 },
      name: "Harf Sayısı",
      min: "1",
      max: "10",
      required: false,
      asyncList: getWordListByLetterCount,
      description: "Metindeki harf sayısı",
      styleClass: "!mb-0",
    },
    {
      type: "checkbox",
      inputKey: "scroll",
      value: { key: "scroll", type: "boolean", value: false },
      name: "Kaydırma",
      description: "Kelime yukarıdan aşağıya kaysın mı?",
      styleClass: "!mb-0",
    },
  ],
  metronom: [
    {
      type: "range",
      inputKey: "level",
      value: { key: "level", type: "number", value: 1 },
      name: "Hız",
      min: "1",
      max: "10",
      required: false,
      valueMap: speedMap,
      description: "Nesnenin hareket hızı",
      styleClass: "!mb-0",
    },
  ],
  "dogru-rengi-bul": [
    {
      type: "range",
      inputKey: "level",
      value: { key: "level", type: "number", value: 1 },
      name: "Hız",
      min: "1",
      max: "10",
      required: false,
      valueMap: speedMap,
      description: "Nesnenin hareket hızı",
      styleClass: "!mb-0",
    },
    {
      type: "display",
      inputKey: "resultDisplay",
      value: { key: "resultDisplay", type: "object", value: {} },
      styleClass: "!mb-0",
    },
  ],
  "dogru-kelimeyi-bil": [
    {
      type: "range",
      inputKey: "level",
      value: { key: "level", type: "number", value: 1 },
      name: "Hız",
      min: "1",
      max: "10",
      required: false,
      valueMap: speedMap,
      description: "Nesnenin hareket hızı",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "difficultyLevel",
      value: { key: "difficultyLevel", type: "number", value: 1 },
      name: "Zorluk",
      min: "1",
      max: "6",
      required: false,
      description: "Zorluk durumu",
      styleClass: "!mb-0",
    },
    {
      type: "display",
      inputKey: "resultDisplay",
      value: { key: "resultDisplay", type: "object", value: {} },
      styleClass: "!mb-0",
    },
  ],
  "dogru-sayiyi-bul": [
    {
      type: "range",
      inputKey: "level",
      value: { key: "level", type: "number", value: 1 },
      name: "Hız",
      min: "1",
      max: "10",
      required: false,
      valueMap: speedMap,
      description: "Nesnenin hareket hızı",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "difficultyLevel",
      value: { key: "difficultyLevel", type: "number", value: 1 },
      name: "Zorluk",
      min: "1",
      max: "6",
      required: false,
      description: "Zorluk durumu",
      styleClass: "!mb-0",
    },
    {
      type: "display",
      inputKey: "resultDisplay",
      value: { key: "resultDisplay", type: "object", value: {} },
      styleClass: "!mb-0",
    },
  ],
  "hizli-gorme": [
    {
      type: "range",
      inputKey: "wordsPerFrame",
      value: { key: "wordsPerFrame", type: "number", value: 1 },
      name: "Kelime sayısı",
      min: "1",
      max: "5",
      required: false,
      description:
        "Yükselttikçe aynı anda görebileceğiniz kelime sayısı artar.",
      styleClass: "!mb-0",
      asyncList: getWordListPerCount,
    },
    {
      type: "range",
      inputKey: "level",
      value: { key: "level", type: "number", value: 1 },
      name: "Hız",
      min: "1",
      max: "10",
      required: false,
      valueMap: speedMap,
      description: "Nesnenin hareket hızı",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "font",
      value: { key: "font", type: "number", value: 16 },
      name: "Font",
      min: "16",
      max: "32",
      steps: "2",
      required: false,
      description:
        "Yazı karekterinin büyüklüğü, okuma zorluğu çekiyorsanız büyütün",
      styleClass: "!mb-0",
    },
  ],
  "goz-cevikligi-artirma": [
    {
      type: "range",
      inputKey: "wordsPerFrame",
      value: { key: "wordsPerFrame", type: "number", value: 1 },
      name: "Kelime sayısı",
      min: "1",
      max: "5",
      required: false,
      description:
        "Yükselttikçe aynı anda görebileceğiniz kelime sayısı artar.",
      styleClass: "!mb-0",
      asyncList: getWordListPerCount,
    },
    {
      type: "range",
      inputKey: "level",
      value: { key: "level", type: "number", value: 1 },
      name: "Hız",
      min: "1",
      max: "10",
      required: false,
      valueMap: speedMap,
      description: "Nesnenin hareket hızı",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "font",
      value: { key: "font", type: "number", value: 16 },
      name: "Font",
      min: "16",
      max: "32",
      steps: "2",
      required: false,
      description:
        "Yazı karekterinin büyüklüğü, okuma zorluğu çekiyorsanız büyütün",
      styleClass: "!mb-0",
    },
  ],
  "seviye-yukselt": [
    {
      type: "range",
      inputKey: "wordsPerFrame",
      value: { key: "wordsPerFrame", type: "number", value: 1 },
      name: "Kelime sayısı",
      min: "1",
      max: "5",
      required: false,
      description:
        "Yükselttikçe aynı anda görebileceğiniz kelime sayısı artar.",
      styleClass: "!mb-0",
      asyncList: getWordListPerCount,
    },
    {
      type: "range",
      inputKey: "level",
      value: { key: "level", type: "number", value: 1 },
      name: "Hız",
      min: "1",
      max: "10",
      required: false,
      valueMap: speedMap,
      description: "Nesnenin hareket hızı",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "font",
      value: { key: "font", type: "number", value: 16 },
      name: "Font",
      min: "16",
      max: "32",
      steps: "2",
      required: false,
      description:
        "Yazı karekterinin büyüklüğü, okuma zorluğu çekiyorsanız büyütün",
      styleClass: "!mb-0",
    },
  ],
  "silinmeden-okuma": [
    {
      type: "select",
      inputKey: "categorySelect",
      value: { key: "categorySelect", type: "string", value: "" },
      name: "Makale Kategorisi Seçiniz",
      required: false,
      placeholder: "Makale Kategorisi Seçiniz",
      showLabel: false,
      disabled: false,
      asyncOption: getCategoryOptions,
      styleClass: "!mb-0",
    },
    {
      type: "select",
      inputKey: "articleSelect",
      value: { key: "articleSelect", type: "string", value: "" },
      name: "Makale Kategorisi Seçiniz",
      required: false,
      placeholder: "Makale Seçebilmek için Önce Kategori Seçmelisiniz",
      showLabel: false,
      disabled: false,
      options: [],
      styleClass: "!mb-0",
      asyncOptionById: getArticleOptionsByCategoryId,
      optionId: null,
    },
    {
      type: "range",
      inputKey: "wordsPerFrame",
      value: { key: "wordsPerFrame", type: "number", value: 1 },
      name: "Kelime sayısı",
      min: "1",
      max: "5",
      required: false,
      description:
        "Yükselttikçe aynı anda görebileceğiniz kelime sayısı artar.",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "level",
      value: { key: "level", type: "number", value: 1 },
      name: "Hız",
      min: "1",
      max: "10",
      required: false,
      valueMap: speedMap,
      description: "Nesnenin hareket hızı",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "font",
      value: { key: "font", type: "number", value: 16 },
      name: "Font",
      min: "16",
      max: "32",
      steps: "2",
      required: false,
      description:
        "Yazı karekterinin büyüklüğü, okuma zorluğu çekiyorsanız büyütün",
      styleClass: "!mb-0",
    },
  ],
  "silinerek-okuma": [
    {
      type: "select",
      inputKey: "categorySelect",
      value: { key: "categorySelect", type: "string", value: "" },
      name: "Makale Kategorisi Seçiniz",
      required: false,
      placeholder: "Makale Kategorisi Seçiniz",
      showLabel: false,
      disabled: false,
      asyncOption: getCategoryOptions,
      styleClass: "!mb-0",
    },
    {
      type: "select",
      inputKey: "articleSelect",
      value: { key: "articleSelect", type: "string", value: "" },
      name: "Makale Kategorisi Seçiniz",
      required: false,
      placeholder: "Makale Seçebilmek için Önce Kategori Seçmelisiniz",
      showLabel: false,
      disabled: false,
      options: [],
      asyncOptionById: getArticleOptionsByCategoryId,
      optionId: null,
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "wordsPerFrame",
      value: { key: "wordsPerFrame", type: "number", value: 1 },
      name: "Kelime sayısı",
      min: "1",
      max: "5",
      required: false,
      description:
        "Yükselttikçe aynı anda görebileceğiniz kelime sayısı artar.",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "level",
      value: { key: "level", type: "number", value: 1 },
      name: "Hız",
      min: "1",
      max: "10",
      required: false,
      valueMap: speedMap,
      description: "Nesnenin hareket hızı",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "font",
      value: { key: "font", type: "number", value: 16 },
      name: "Font",
      min: "16",
      max: "32",
      steps: "2",
      required: false,
      description:
        "Yazı karekterinin büyüklüğü, okuma zorluğu çekiyorsanız büyütün",
      styleClass: "!mb-0",
    },
  ],
  "odakli-okuma": [
    {
      type: "select",
      inputKey: "categorySelect",
      value: { key: "categorySelect", type: "string", value: "" },
      name: "Makale Kategorisi Seçiniz",
      required: false,
      placeholder: "Makale Kategorisi Seçiniz",
      showLabel: false,
      disabled: false,
      asyncOption: getCategoryOptions,
      styleClass: "!mb-0",
    },
    {
      type: "select",
      inputKey: "articleSelect",
      value: { key: "articleSelect", type: "string", value: "" },
      name: "Makale Kategorisi Seçiniz",
      required: false,
      placeholder: "Makale Seçebilmek için Önce Kategori Seçmelisiniz",
      showLabel: false,
      disabled: false,
      options: [],
      asyncOptionById: getArticleOptionsByCategoryId,
      optionId: null,
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "wordsPerFrame",
      value: { key: "wordsPerFrame", type: "number", value: 1 },
      name: "Kelime sayısı",
      min: "1",
      max: "5",
      required: false,
      description:
        "Yükselttikçe aynı anda görebileceğiniz kelime sayısı artar.",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "level",
      value: { key: "level", type: "number", value: 1 },
      name: "Hız",
      min: "1",
      max: "10",
      required: false,
      valueMap: speedMap,
      description: "Nesnenin hareket hızı",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "font",
      value: { key: "font", type: "number", value: 16 },
      name: "Font",
      min: "16",
      max: "32",
      steps: "2",
      required: false,
      description:
        "Yazı karekterinin büyüklüğü, okuma zorluğu çekiyorsanız büyütün",
      styleClass: "!mb-0",
    },
  ],
  "grup-okuma": [
    {
      type: "select",
      inputKey: "categorySelect",
      value: { key: "categorySelect", type: "string", value: "" },
      name: "Makale Kategorisi Seçiniz",
      required: false,
      placeholder: "Makale Kategorisi Seçiniz",
      showLabel: false,
      disabled: false,
      asyncOption: getCategoryOptions,
      styleClass: "!mb-0",
    },
    {
      type: "select",
      inputKey: "articleSelect",
      value: { key: "articleSelect", type: "string", value: "" },
      name: "Makale Kategorisi Seçiniz",
      required: false,
      placeholder: "Makale Seçebilmek için Önce Kategori Seçmelisiniz",
      showLabel: false,
      disabled: false,
      options: [],
      asyncOptionById: getArticleOptionsByCategoryId,
      optionId: null,
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "wordsPerFrame",
      value: { key: "wordsPerFrame", type: "number", value: 1 },
      name: "Kelime sayısı",
      min: "1",
      max: "5",
      required: false,
      description:
        "Yükselttikçe aynı anda görebileceğiniz kelime sayısı artar.",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "level",
      value: { key: "level", type: "number", value: 1 },
      name: "Hız",
      min: "1",
      max: "10",
      required: false,
      valueMap: speedMap,
      description: "Nesnenin hareket hızı",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "font",
      value: { key: "font", type: "number", value: 16 },
      name: "Font",
      min: "16",
      max: "32",
      steps: "2",
      required: false,
      description:
        "Yazı karekterinin büyüklüğü, okuma zorluğu çekiyorsanız büyütün",
      styleClass: "!mb-0",
    },
  ],
  "hizli-okuma-testi": [
    {
      type: "select",
      inputKey: "categorySelect",
      value: { key: "categorySelect", type: "string", value: "" },
      name: "Makale Kategorisi Seçiniz",
      required: false,
      placeholder: "Makale Kategorisi Seçiniz",
      showLabel: false,
      disabled: false,
      asyncOption: getCategoryOptions,
      styleClass: "!mb-0",
    },
    {
      type: "select",
      inputKey: "articleSelect",
      value: { key: "articleSelect", type: "string", value: "" },
      name: "Makale Kategorisi Seçiniz",
      required: false,
      placeholder: "Makale Seçebilmek için Önce Kategori Seçmelisiniz",
      showLabel: false,
      disabled: false,
      options: [],
      asyncOptionById: getArticleOptionsByCategoryId,
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "wordsPerFrame",
      value: { key: "wordsPerFrame", type: "number", value: 1 },
      name: "Kelime sayısı",
      min: "1",
      max: "5",
      required: false,
      description:
        "Yükselttikçe aynı anda görebileceğiniz kelime sayısı artar.",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "level",
      value: { key: "level", type: "number", value: 1 },
      name: "Hız",
      min: "1",
      max: "10",
      required: false,
      valueMap: speedMap,
      description: "Nesnenin hareket hızı",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "font",
      value: { key: "font", type: "number", value: 16 },
      name: "Font",
      min: "16",
      max: "32",
      steps: "2",
      required: false,
      styleClass: "text-white !mb-0",
    },
  ],
  "anlama-testi": [
    {
      type: "select",
      inputKey: "categorySelect",
      value: { key: "categorySelect", type: "string", value: "" },
      name: "Makale Kategorisi Seçiniz",
      required: false,
      placeholder: "Makale Kategorisi Seçiniz",
      showLabel: false,
      disabled: false,
      asyncOption: getCategoryOptions,
      styleClass: "!mb-0",
    },
    {
      type: "select",
      inputKey: "articleSelect",
      value: { key: "articleSelect", type: "string", value: "" },
      name: "Makale Kategorisi Seçiniz",
      required: false,
      placeholder: "Makale Seçebilmek için Önce Kategori Seçmelisiniz",
      showLabel: false,
      disabled: false,
      options: [],
      asyncOptionById: getArticleOptionsByCategoryId,
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "wordsPerFrame",
      value: { key: "wordsPerFrame", type: "number", value: 1 },
      name: "Kelime sayısı",
      min: "1",
      max: "5",
      required: false,
      description:
        "Yükselttikçe aynı anda görebileceğiniz kelime sayısı artar.",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "level",
      value: { key: "level", type: "number", value: 1 },
      name: "Hız",
      min: "1",
      max: "10",
      required: false,
      valueMap: speedMap,
      description: "Nesnenin hareket hızı",
      styleClass: "!mb-0",
    },
    {
      type: "range",
      inputKey: "font",
      value: { key: "font", type: "number", value: 16 },
      name: "Font",
      min: "16",
      max: "32",
      steps: "2",
      required: false,
      styleClass: "text-white !mb-0",
    },
  ],
};
