export const lessons = {
  "1": [
    {
      name: "Ritmini Renklendirme",
      link: "/goz-egzersiz/ritmini-renklendirme",
    },
    { name: "Kelimeler-1", link: "/okuma-egzersiz/kelimeler-1" },
    { name: "Sayılar-1", link: "/okuma-egzersiz/sayilar-1" },
    { name: "Sayılar-2", link: "/okuma-egzersiz/sayilar-2" },
    { name: "Sayılar-3", link: "/okuma-egzersiz/sayilar-3" },
    { name: "Takistoskop", link: "/takistoskop/hizli-gorme" },
    { name: "Hızlı Okuma Testi", link: "/goster-kendini/hizli-okuma-testi" },
  ],
  "2": [
    { name: "Siyah-Beyaz", link: "/goz-egzersiz/siyah-beyaz" },
    { name: "Geniş Bakış", link: "/goz-egzersiz/genis-bakis" },
    { name: "Kelimeler-1", link: "/okuma-egzersiz/kelimeler-1" },
    { name: "Sayılar-2", link: "/okuma-egzersiz/sayilar-2" },
    { name: "Sayılar-3", link: "/okuma-egzersiz/sayilar-3" },
    { name: "Takistoskop", link: "/takistoskop/hizli-gorme" },
    { name: "Anlama Tesi", link: "/goster-kendini/anlama-testi" },
  ],
  "3": [
    { name: "Kelimeler-1", link: "/okuma-egzersiz/kelimeler-1" },
    { name: "Kelimeler-5", link: "/okuma-egzersiz/kelimeler-5" },
    { name: "Sayılar-1", link: "/okuma-egzersiz/sayilar-1" },
    { name: "Sayılar-2", link: "/okuma-egzersiz/sayilar-2" },
    { name: "Sayılar-3", link: "/okuma-egzersiz/sayilar-3" },
    { name: "Takistoskop", link: "/takistoskop/hizli-gorme" },
    { name: "Hızlı Okuma Testi", link: "/goster-kendini/hizli-okuma-testi" },
  ],
  "4": [
    { name: "Siyah-Beyaz", link: "/goz-egzersiz/siyah-beyaz" },
    { name: "Geniş Bakış", link: "/goz-egzersiz/genis-bakis" },
    { name: "Kelimeler-1", link: "/okuma-egzersiz/kelimeler-1" },
    { name: "Sayılar-2", link: "/okuma-egzersiz/sayilar-2" },
    { name: "Sayılar-3", link: "/okuma-egzersiz/sayilar-3" },
    { name: "Takistoskop", link: "/takistoskop/hizli-gorme" },
    { name: "Anlama Tesi", link: "/goster-kendini/anlama-testi" },
  ],
};
export const letterWords = [
  "bal",
  "suç",
  "kar",
  "ses",
  "tuz",
  "yol",
  "can",
  "dal",
  "cam",
  "kan",
  "göl",
  "kor",
  "kız",
  "kıl",
  "çam",
  "çay",
  "göz",
  "ağa",
  "yer",
  "gün",
  "masa",
  "yazı",
  "kafa",
  "kapı",
  "ayna",
  "tava",
  "yara",
  "kedi",
  "dolu",
  "yaka",
  "dost",
  "şair",
  "çile",
  "baba",
  "kale",
  "para",
  "gemi",
  "saat",
  "pati",
  "hava",
  "kalem",
  "uçmak",
  "kavun",
  "çiçek",
  "deniz",
  "gölge",
  "simit",
  "yemek",
  "sabah",
  "akşam",
  "diken",
  "sesli",
  "kitap",
  "korku",
  "sevgi",
  "tatlı",
  "sütlü",
  "pudra",
  "orman",
  "okuma",
  "kalmak",
  "çiğdem",
  "balina",
  "yağmur",
  "gülmek",
  "karpuz",
  "sahile",
  "komşum",
  "rüzgar",
  "örsler",
  "bakkal",
  "mutfak",
  "yazlık",
  "kışlık",
  "oyuncu",
  "okulda",
  "bahçem",
  "çorbac",
  "çiftçi",
  "çalışa",
  "arkadaş",
  "düşünce",
  "güneşli",
  "yağmurlu",
  "bahçeci",
  "kitapçı",
  "sevginin",
  "umutları",
  "koşullar",
  "balıklar",
  "denizler",
  "özgürlük",
  "şarkılar",
  "öğrenci",
  "öyküler",
  "sonbahar",
  "sevinçli",
  "cesaretl",
  "gözlemci",
  "yardımse",
];

export const letterNumbers = {
  "sayilar-1": [
    "123",
    "234",
    "345",
    "456",
    "567",
    "678",
    "789",
    "890",
    "901",
    "999",
    "101",
    "232",
    "334",
    "744",
    "565",
    "676",
    "877",
    "988",
    "912",
    "321",
  ],
  "sayilar-2": [
    "1234",
    "2345",
    "3456",
    "4567",
    "5678",
    "6789",
    "7890",
    "8901",
    "9012",
    "9790",
    "1411",
    "2922",
    "3133",
    "6414",
    "5056",
    "1667",
    "3773",
    "8081",
    "9123",
    "3210",
  ],
  "sayilar-3": [
    "12345",
    "23456",
    "34567",
    "45678",
    "56789",
    "67890",
    "78901",
    "89012",
    "90123",
    "99999",
    "10131",
    "23226",
    "38331",
    "24644",
    "58550",
    "66266",
    "27577",
    "28886",
    "91234",
    "32109",
  ],
  "sayilar-4": [
    "123456",
    "234567",
    "345678",
    "456789",
    "567890",
    "678901",
    "789012",
    "890123",
    "901234",
    "997996",
    "141411",
    "232426",
    "357133",
    "454749",
    "554535",
    "663660",
    "700772",
    "808080",
    "912345",
    "321098",
  ],
  "sayilar-5": [
    "1234567",
    "2345678",
    "3456789",
    "4567890",
    "5678901",
    "6789012",
    "7890123",
    "8901234",
    "9012345",
    "9098909",
    "1100117",
    "2426227",
    "3533343",
    "4400454",
    "5356755",
    "7676866",
    "7876757",
    "8982881",
    "9123456",
    "3210987",
  ],
};
export const playlists = [
  {
    type: "audio/mpeg",
    src: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Vivaldi_-_Four_Seasons_1_Spring_mvt_1_Allegro_-_John_Harrison_violin.oga",
  },
  {
    type: "audio/mpeg",
    src: "https://www.coothead.co.uk/audio/You-Cant-Always-Get-What-You-Want.mp3",
  },
];

type ExerciseDescription = {
  description: string;
  howToPlay: string;
};
type EyeExerciseDescriptionMap = Record<string, ExerciseDescription>;
export const eyeExerciseDescription: EyeExerciseDescriptionMap = {
  "goz-kaslarini-gelistirme": {
    description:
      "Gözlerimizde toplam 6 adet kas var. Göz kaslarını geliştirmek için koordineli olarak hareket ettirmek gerekmektedir. Bu uygulamayı günde en az 5 dakika yaparak göz kaslarınızı geliştirebilirsiniz.",

    howToPlay:
      "<p> Alttaki araçlardan hız, egzersiz tipi ve simgeyi seçip  <span style='color:blue'>►</span> butonuna basarak uygulamayı başlatın. Bilgisayarı tam karşınıza alarak, başınızı hareket ettirmeden sadece gözleriniz ile ekrandaki simgeyi süre bitene kadar takip edin.</p>",
  },

  "aktif-gorme-alanini-genisletme-1": {
    description:
      "Gözlerimiz bir tek şey üzerinde odaklanmış olsa bile, o cismin çevresinde olan bir sürü bilgiyi de algılama yeteneğine sahiptir. Gözlerini iyi eğiten bir okuyucu aktif görme alanını tam olarak kullanabilir. Bu egzersiz ile gözümüzün görme alanını 4 tarafa doğru geliştirebiliriz.",
    howToPlay:
      "<p>Alttaki araçlardan çerçeve genişliği, sütun sayısı ve hızı ayarlayıp <span style='color:blue'>►</span> butonuna basarak uygulamayı başlatın. Rakamların ortasındaki noktaya bakarak bütün rakamları görmeye çalışın. Rakamları seslendirmeden sadece görün. Süre bitene kadar egzersize devam edin.</p>",
  },
  "aktif-gorme-alanini-genisletme-2": {
    description:
      "Gözlerimiz bir tek şey üzerinde odaklanmış olsa bile, o cismin çevresinde olan bir sürü bilgiyi de algılama yeteneğine sahiptir. Gözlerini iyi eğiten bir okuyucu aktif görme alanını tam olarak kullanabilir. Bu egzersiz ile gözümüzün görme alanını 4 tarafa doğru geliştirebiliriz.",
    howToPlay:
      "<p>Alttaki araçlardan hız ve kutu rengini ayarlayıp <span style='color:blue'>►</span> butonuna basarak uygulamayı başlatın. Karenin ortasına bakarak bütün kareyi görmeye çalışın. Süre bitene kadar egzersize devam edin.",
  },
  "aktif-gorme-alanini-genisletme-3": {
    description:
      "Gözlerimiz bir tek şey üzerinde odaklanmış olsa bile, o cismin çevresinde olan bir sürü bilgiyi de algılama yeteneğine sahiptir. Gözlerini iyi eğiten bir okuyucu aktif görme alanını tam olarak kullanabilir. Bu egzersiz ile gözümüzün görme alanını 4 tarafa doğru geliştirebiliriz.",
    howToPlay:
      "Alttaki araçlardan hızı ayarlayıp <span style='color:blue'>►</span> butonuna basarak uygulamayı başlatın. Karenin ortasına bakarak bütün kareleri görmeye çalışın. Süre bitene kadar egzersize devam edin.",
  },
  metronom: {
    description:
      "Metronom çok eski bir eğitim aracıdır. Özellikle konuşma bozukluklarına iyi gelen bu uygulamadır. Hızlı okuma ve algılamanın yanı sıra, dikkat ve odaklanmayı da arttırır.",
    howToPlay:
      "<p>Metronom hızını seçip <span style='color:blue'>►</span> butonuna basın ve uygulamaya başlayın.",
  },
  "satir-boyu-gorme-uygulamasi": {
    description:
      "Bu uygulama ile gözün satır boyunca daha geniş bir alanı görmesini sağlayabilirsiniz.",
    howToPlay:
      "<p>Alttaki araçlardan merkeze uzaklık, harf Sayısı ve hız ayarlarınızı yapıp <span style='color:blue'>►</span> butonuna basarak uygulamayı başlatın. Ekranın ortasında ki çizgiye odaklanarak kenarlardaki kelime ve kelime gruplarını gözlerinizi hareket etmeden okuyun. Süre bitene kadar egzersize devam edin.</p>",
  },
};

export const speedMap: Record<number, number> = {
  1: 600,
  2: 500,
  3: 450,
  4: 425,
  5: 400,
  6: 380,
  7: 370,
  8: 320,
  9: 260,
  10: 220,
};

export const studyGroupOptions = [
  { value: "ILKOKUL_2_3", name: "İlkokul (2-3)" },
  { value: "ILKOKUL_4", name: "İlkokul (4)" },
  { value: "ORTAOKUL", name: "Ortaokul" },
  { value: "LISE", name: "Lise" },
  { value: "UNIVERSITE", name: "Üniversite" },
  { value: "DOKTORA", name: "Doktora" },
  { value: "GENEL", name: "Genel" },
  { value: "YETISKIN", name: "Yetişkin" },
  { value: "DISLEKSI", name: "Disleksi" },
  { value: "TIP", name: "Tıp" },
  { value: "IELTS", name: "IELTS" },
  { value: "LGS_HAZIRLIK", name: "LGS Hazırlık" },
  { value: "TYT_AYT_HAZIRLIK", name: "TYT-AYT Hazırlık" },
  { value: "DEMO", name: "Demo" },
];

type ColorItem = {
  word: string;
  color: string;
};
export const COLORS: ColorItem[] = [
  { word: "SİYAH", color: "black" },
  { word: "KIRMIZI", color: "red" },
  { word: "YEŞİL", color: "green" },
  { word: "MAVİ", color: "blue" },
  { word: "SARI", color: "yellow" },
  { word: "TURUNCU", color: "orange" },
  { word: "MOR", color: "purple" },
];
