export const lessons = {
  "1": [
    {
      name: "Ritmini Renklendirme",
      link: "/goz-egzersiz/ritmini-renklendirme",
    },
    { name: "Kelimeler-1", link: "/okuma-egzersiz/kelimeler-1" },
    { name: "Sayılar-1", link: "/okuma-egzersiz/sayilar-1" },
    { name: "Sayılar-2", link: "/okuma-egzersiz/sayilar-2" },
    { name: "Sayılar-3", link: "/okuma-egzersiz/sayilar-3" },
    { name: "Takistoskop", link: "/takistoskop/hizli-gorme" },
    { name: "Göster Kendini", link: "/goster-kendini" },
  ],
  "2": [
    { name: "Siyah-Beyaz", link: "/goz-egzersiz/siyah-beyaz" },
    { name: "Geniş Bakış", link: "/goz-egzersiz/genis-bakis" },
    { name: "Kelimeler-1", link: "/okuma-egzersiz/kelimeler-1" },
    { name: "Sayılar-2", link: "/okuma-egzersiz/sayilar-2" },
    { name: "Sayılar-3", link: "/okuma-egzersiz/sayilar-3" },
    { name: "Takistoskop", link: "/takistoskop/hizli-gorme" },
    { name: "Göster Kendini", link: "/goster-kendini" },
  ],
  "3": [
    { name: "Kelimeler-1", link: "/okuma-egzersiz/kelimeler-1" },
    { name: "Kelimeler-5", link: "/okuma-egzersiz/kelimeler-5" },
    { name: "Sayılar-1", link: "/okuma-egzersiz/sayilar-1" },
    { name: "Sayılar-2", link: "/okuma-egzersiz/sayilar-2" },
    { name: "Sayılar-3", link: "/okuma-egzersiz/sayilar-3" },
    { name: "Takistoskop", link: "/takistoskop/hizli-gorme" },
    { name: "Göster Kendini", link: "/goster-kendini" },
  ],
};
export const letterWords = {
  "kelimeler-1": [
    "bal",
    "suç",
    "kar",
    "ses",
    "tuz",
    "yol",
    "can",
    "dal",
    "cam",
    "kan",
    "göl",
    "kor",
    "kız",
    "kıl",
    "çam",
    "çay",
    "göz",
    "ağa",
    "yer",
    "gün",
  ],
  "kelimeler-2": [
    "masa",
    "yazı",
    "kafa",
    "kapı",
    "ayna",
    "tava",
    "yara",
    "kedi",
    "dolu",
    "yaka",
    "dost",
    "şair",
    "çile",
    "baba",
    "kale",
    "para",
    "gemi",
    "saat",
    "pati",
    "hava",
  ],
  "kelimeler-3": [
    "kalem",
    "uçmak",
    "kavun",
    "çiçek",
    "deniz",
    "gölge",
    "simit",
    "yemek",
    "sabah",
    "akşam",
    "diken",
    "sesli",
    "kitap",
    "korku",
    "sevgi",
    "tatlı",
    "sütlü",
    "pudra",
    "orman",
    "okuma",
  ],
  "kelimeler-4": [
    "kalmak",
    "çiğdem",
    "balina",
    "yağmur",
    "gülmek",
    "karpuz",
    "sahile",
    "komşum",
    "rüzgar",
    "örsler",
    "bakkal",
    "mutfak",
    "yazlık",
    "kışlık",
    "oyuncu",
    "okulda",
    "bahçem",
    "çorbac",
    "çiftçi",
    "çalışa",
  ],
  "kelimeler-5": [
    "arkadaş",
    "düşünce",
    "güneşli",
    "yağmurlu",
    "bahçeci",
    "kitapçı",
    "sevginin",
    "umutları",
    "koşullar",
    "balıklar",
    "denizler",
    "özgürlük",
    "şarkılar",
    "öğrenci",
    "öyküler",
    "sonbahar",
    "sevinçli",
    "cesaretl",
    "gözlemci",
    "yardımse",
  ],
};
export const letterNumbers = {
  "sayilar-1": [
    "123",
    "234",
    "345",
    "456",
    "567",
    "678",
    "789",
    "890",
    "901",
    "999",
    "101",
    "232",
    "334",
    "744",
    "565",
    "676",
    "877",
    "988",
    "912",
    "321",
  ],
  "sayilar-2": [
    "1234",
    "2345",
    "3456",
    "4567",
    "5678",
    "6789",
    "7890",
    "8901",
    "9012",
    "9790",
    "1411",
    "2922",
    "3133",
    "6414",
    "5056",
    "1667",
    "3773",
    "8081",
    "9123",
    "3210",
  ],
  "sayilar-3": [
    "12345",
    "23456",
    "34567",
    "45678",
    "56789",
    "67890",
    "78901",
    "89012",
    "90123",
    "99999",
    "10131",
    "23226",
    "38331",
    "24644",
    "58550",
    "66266",
    "27577",
    "28886",
    "91234",
    "32109",
  ],
  "sayilar-4": [
    "123456",
    "234567",
    "345678",
    "456789",
    "567890",
    "678901",
    "789012",
    "890123",
    "901234",
    "997996",
    "141411",
    "232426",
    "357133",
    "454749",
    "554535",
    "663660",
    "700772",
    "808080",
    "912345",
    "321098",
  ],
  "sayilar-5": [
    "1234567",
    "2345678",
    "3456789",
    "4567890",
    "5678901",
    "6789012",
    "7890123",
    "8901234",
    "9012345",
    "9098909",
    "1100117",
    "2426227",
    "3533343",
    "4400454",
    "5356755",
    "7676866",
    "7876757",
    "8982881",
    "9123456",
    "3210987",
  ],
};
export const playlists = [
  {
    type: "audio/mpeg",
    src: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Vivaldi_-_Four_Seasons_1_Spring_mvt_1_Allegro_-_John_Harrison_violin.oga",
  },
  {
    type: "audio/mpeg",
    src: "https://www.coothead.co.uk/audio/You-Cant-Always-Get-What-You-Want.mp3",
  },
];

export const sampleText =
  "text example a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and small write a scrollingReading react component that take text and level as props It dispalys the text and gradually scroll the text up according to the level of speed provided. At the same time make floating circle move in a wave like motion from left to right and then move a row down untill it get to the last row of the text. the circle should be red and smal";
